apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hypershift-iam-config
  namespace: cluster-provisioning
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: hypershift-iam-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.hypershiftIAM.key }}
