apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: global-pullsecret
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: global-pullsecret
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: {{ .Values.pullSecret.key }}
      property: docker
