apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  finalizers:
  - finalizers.s3.services.k8s.aws/Bucket
  labels:
{{- if (gt (len .Values.s3.additionalTags) 0) -}}
  {{- range $key, $value := .Values.s3.additionalTags }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
  name: {{ .Values.s3.bucketName }}
  namespace: {{ .Values.s3.bucketNamespace | default "ack-system" }}
spec:
  name: {{ .Values.s3.bucketName }}
{{- if eq .Values.s3.createBucketPolicy true | default true }}
  policy: >-
    {{ include "ack-s3-controller.bucket_policy" . }}
{{- end }}
