{{- if .Values.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: test-eso
  namespace: ack-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: testack-s3-user-secrets
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY:  "{{ .aws_secret_access_key }}"
data:
- secretKey: aws_access_key_id
  remoteRef:
    key: {{ .Values.awscredentials.key }}
    property: aws_access_key_id
- secretKey: aws_secret_access_key
  remoteRef:
    key: {{ .Values.awscredentials.key }}
    property: aws_secret_access_key
      
{{- end }}
