kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hcp-cli
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  source:
    type: Git
    git:
      uri: https://github.com/validatedpatterns-sandbox/hypershift
      ref: hypershift-mce
    contextDir: containerfiles
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile 
  triggers:
  - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: hcp-cli:latest

