letsencrypt:
  region: us-east-2 # region of the cluster
  server: https://acme-v02.api.letsencrypt.org/directory
  # staging URL
  # server: https://acme-staging-v02.api.letsencrypt.org/directory
  email: team-vp@ragtagrobot.com

clusterGroup:
  applications:
    letsencrypt:
      disabled: false
      name: letsencrypt
      namespace: letsencrypt
      project: default
      path: common/letsencrypt