---
global:
  pattern: hypershift
  singleArgoCD: true

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  variant: staging
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
