---
global:
  pattern: hypershift

  sharedValueFiles:
   - /values-hypershift.yaml

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
