# Override values for HyperShift 
global:
  useExternalSecrets: true
  s3:
    createBucket: true
    region: us-west-1
    bucketName: jrickard-hcp-demo
    additionalTags:
      owner: jrickard
      destroy: true
  
  buildconfig:
    git:
      uri: https://github.com/validatedpatterns-sandbox/hypershift
