# Default values for hypershift.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
useExternalSecrets: true

s3:
  region: 
  bucketName: 
  createBucketPolicy: true
  additionalTags: []

# Parameters for the imagestream
imagestream:
  sourceImage: image-registry.openshift-image-registry.svc:5000/openshift/cli
  tag: latest

# Parameters for the buildconfig
buildconfig:
  git:
    uri: https://github.com/validatedpatterns-sandbox/hypershift
    contextDir: containerfiles
  dockerfilePath: Containerfile
  triggers: ConfigChange

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the HyperShift installation 
awsCredentials:
  key: secret/data/hub/awsCreds
