# Default values for hypershift.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

awscredentials:
  key: secret/data/hub/aws

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true
