# Default values for hypershift.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
hcp:
  serviceAccount: hcp-sa

s3:
  region: us-west-2
  bucketName: hypershifttest-hcp #default-bucket-hcp
  
createBucketPolicy: true
additionalTags: []

# Parameters for the imagestream
imagestream:
  sourceImage: image-registry.openshift-image-registry.svc:5000/openshift/cli
  tag: latest

# Parameters for the buildconfig
buildconfig:
  git:
    uri: https://github.com/validatedpatterns-sandbox/hypershift
    ref: hypershift-mce
    contextDir: containerfiles
  dockerfilePath: Containerfile
  triggers: ConfigChange

ackS3:
  ack_enable_development_logging: true
  ack_log_level: debug
  ack_watch_namespace: 
  ack_resource_tags: acktagged
  ack_endpoint_url: 
  enable_leader_election: true
  leader_election_namespace:

global:
  hubClusterDomain: hub.example.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the AWS Controller for Kubernetes - S3 
ackCredentials:
  key: secret/data/hub/aws

# Secret provisioned for the HyperShift installation 
awsCredentials:
  key: secret/data/hub/awsCreds
