apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: destroy-hive-
  namespace: cluster-provisioning
spec:
  pipelineRef:
    name: destroy-hive-cluster
  params:
  - name: cluster-name
    value: hivetest
  - name: timeout-minutes
    value: "30"
  - name: delete-namespace
    value: "true"
  taskRunTemplate:
    serviceAccountName: provisioner
