apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - github:
      clientID: {{ .Values.github.accessKey }}
      clientSecret:
        name: {{ .Values.oauthSecretName }}
      organizations:
{{- range .Values.github.orgs }}
      - {{ .name }}
{{- end }}
    mappingMethod: claim
    name: github
    type: GitHub
  tokenConfig:
    accessTokenMaxAgeSeconds: 62208000

